### ISSUE TITLE
추가 기능이 필요합니다

### ISSUE THREAD

**Issue by soondl** [onting/SE_backend#15]
*  광고 이미지
프론트에 표시할 광고 이미지. 총 4개이며 불러오기, 추가, 삭제가 가능
*  product date 최신 순으로 8개 출력
*  product stock 큰 순으로 8개 출력
*  product post 시에 date 함께 입력
*  product hardware, title 구분 없이 출력

**Comment by onting** [comment]
추가했습니다.
